// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: api/message.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetMessage request
type GetMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageRequest) Reset() {
	*x = GetMessageRequest{}
	mi := &file_api_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest) ProtoMessage() {}

func (x *GetMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest.ProtoReflect.Descriptor instead.
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_message_proto_rawDescGZIP(), []int{0}
}

func (x *GetMessageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetMessage response
type GetMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageResponse) Reset() {
	*x = GetMessageResponse{}
	mi := &file_api_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageResponse) ProtoMessage() {}

func (x *GetMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageResponse.ProtoReflect.Descriptor instead.
func (*GetMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_message_proto_rawDescGZIP(), []int{1}
}

func (x *GetMessageResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SubmitMessage request
type SubmitMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitMessageRequest) Reset() {
	*x = SubmitMessageRequest{}
	mi := &file_api_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitMessageRequest) ProtoMessage() {}

func (x *SubmitMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitMessageRequest.ProtoReflect.Descriptor instead.
func (*SubmitMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_message_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitMessageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubmitMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SubmitMessage response
type SubmitMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitMessageResponse) Reset() {
	*x = SubmitMessageResponse{}
	mi := &file_api_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitMessageResponse) ProtoMessage() {}

func (x *SubmitMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitMessageResponse.ProtoReflect.Descriptor instead.
func (*SubmitMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_message_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_message_proto protoreflect.FileDescriptor

const file_api_message_proto_rawDesc = "" +
	"\n" +
	"\x11api/message.proto\x12\x03api\"'\n" +
	"\x11GetMessageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"B\n" +
	"\x12GetMessageResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"D\n" +
	"\x14SubmitMessageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"K\n" +
	"\x15SubmitMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9b\x01\n" +
	"\x0eMessageService\x12?\n" +
	"\n" +
	"GetMessage\x12\x16.api.GetMessageRequest\x1a\x17.api.GetMessageResponse\"\x00\x12H\n" +
	"\rSubmitMessage\x12\x19.api.SubmitMessageRequest\x1a\x1a.api.SubmitMessageResponse\"\x00B\x0eZ\fgrpcdemo/apib\x06proto3"

var (
	file_api_message_proto_rawDescOnce sync.Once
	file_api_message_proto_rawDescData []byte
)

func file_api_message_proto_rawDescGZIP() []byte {
	file_api_message_proto_rawDescOnce.Do(func() {
		file_api_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_message_proto_rawDesc), len(file_api_message_proto_rawDesc)))
	})
	return file_api_message_proto_rawDescData
}

var file_api_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_message_proto_goTypes = []any{
	(*GetMessageRequest)(nil),     // 0: api.GetMessageRequest
	(*GetMessageResponse)(nil),    // 1: api.GetMessageResponse
	(*SubmitMessageRequest)(nil),  // 2: api.SubmitMessageRequest
	(*SubmitMessageResponse)(nil), // 3: api.SubmitMessageResponse
}
var file_api_message_proto_depIdxs = []int32{
	0, // 0: api.MessageService.GetMessage:input_type -> api.GetMessageRequest
	2, // 1: api.MessageService.SubmitMessage:input_type -> api.SubmitMessageRequest
	1, // 2: api.MessageService.GetMessage:output_type -> api.GetMessageResponse
	3, // 3: api.MessageService.SubmitMessage:output_type -> api.SubmitMessageResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_message_proto_init() }
func file_api_message_proto_init() {
	if File_api_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_message_proto_rawDesc), len(file_api_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_message_proto_goTypes,
		DependencyIndexes: file_api_message_proto_depIdxs,
		MessageInfos:      file_api_message_proto_msgTypes,
	}.Build()
	File_api_message_proto = out.File
	file_api_message_proto_goTypes = nil
	file_api_message_proto_depIdxs = nil
}
